"""Initial PostgreSQL warehouse schema. Existing SQLite is imported separately."""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_warehouse"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diagnosis_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_diagnosis_codes_is_deleted"),
        "diagnosis_codes",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fhir_id", sa.String(length=64), nullable=False),
        sa.Column("identifier_system", sa.String(length=255), nullable=False),
        sa.Column("identifier_value", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("organization_type", sa.String(length=64), nullable=False),
        sa.Column(
            "resource",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fhir_id"),
    )
    op.create_index(
        "ix_organization_identifier",
        "organizations",
        ["identifier_system", "identifier_value"],
        unique=True,
    )
    op.create_index(
        op.f("ix_organizations_is_deleted"),
        "organizations",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "patients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fhir_id", sa.String(length=64), nullable=False),
        sa.Column("identifier_system", sa.String(length=255), nullable=False),
        sa.Column("identifier_value", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(length=16), nullable=True),
        sa.Column(
            "resource",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fhir_id"),
    )
    op.create_index(
        "ix_patient_identifier",
        "patients",
        ["identifier_system", "identifier_value"],
        unique=True,
    )
    op.create_index(
        op.f("ix_patients_is_deleted"), "patients", ["is_deleted"], unique=False
    )
    op.create_table(
        "service_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_service_codes_is_deleted"),
        "service_codes",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "coverages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fhir_id", sa.String(length=64), nullable=False),
        sa.Column("beneficiary_id", sa.Integer(), nullable=False),
        sa.Column("payor_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("policy_number", sa.String(length=128), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "resource",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "period_end IS NULL OR period_start IS NULL OR period_end >= period_start",
            name="ck_coverage_period",
        ),
        sa.ForeignKeyConstraint(
            ["beneficiary_id"], ["patients.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["payor_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fhir_id"),
        sa.UniqueConstraint(
            "id", "beneficiary_id", "payor_id", name="uq_coverage_parties"
        ),
    )
    op.create_index(
        op.f("ix_coverages_beneficiary_id"),
        "coverages",
        ["beneficiary_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_coverages_is_deleted"), "coverages", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_coverages_payor_id"), "coverages", ["payor_id"], unique=False
    )
    op.create_table(
        "encounters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fhir_id", sa.String(length=64), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("service_provider_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("encounter_class", sa.String(length=32), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "resource",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "period_end IS NULL OR period_start IS NULL OR period_end >= period_start",
            name="ck_encounter_period",
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["service_provider_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fhir_id"),
        sa.UniqueConstraint("id", "patient_id", name="uq_encounter_patient"),
    )
    op.create_index(
        op.f("ix_encounters_is_deleted"), "encounters", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_encounters_patient_id"), "encounters", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_encounters_service_provider_id"),
        "encounters",
        ["service_provider_id"],
        unique=False,
    )
    op.create_table(
        "insurance_companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("organization_id"),
    )
    op.create_index(
        op.f("ix_insurance_companies_is_deleted"),
        "insurance_companies",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "practitioners",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fhir_id", sa.String(length=64), nullable=False),
        sa.Column("identifier_system", sa.String(length=255), nullable=False),
        sa.Column("identifier_value", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column(
            "resource",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fhir_id"),
    )
    op.create_index(
        "ix_practitioner_identifier",
        "practitioners",
        ["identifier_system", "identifier_value"],
        unique=True,
    )
    op.create_index(
        op.f("ix_practitioners_is_deleted"),
        "practitioners",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_practitioners_organization_id"),
        "practitioners",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "claims",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fhir_id", sa.String(length=64), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("insurer_id", sa.Integer(), nullable=False),
        sa.Column("practitioner_id", sa.Integer(), nullable=True),
        sa.Column("coverage_id", sa.Integer(), nullable=False),
        sa.Column("encounter_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("use", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "resource",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint("total >= 0", name="ck_claim_total_nonnegative"),
        sa.ForeignKeyConstraint(
            ["coverage_id", "patient_id", "insurer_id"],
            ["coverages.id", "coverages.beneficiary_id", "coverages.payor_id"],
            name="fk_claim_coverage_parties",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["coverage_id"], ["coverages.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["encounter_id", "patient_id"],
            ["encounters.id", "encounters.patient_id"],
            name="fk_claim_encounter_patient",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"], ["encounters.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["insurer_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["practitioner_id"], ["practitioners.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fhir_id"),
    )
    op.create_index(
        op.f("ix_claims_coverage_id"), "claims", ["coverage_id"], unique=False
    )
    op.create_index(
        op.f("ix_claims_encounter_id"), "claims", ["encounter_id"], unique=False
    )
    op.create_index(
        op.f("ix_claims_insurer_id"), "claims", ["insurer_id"], unique=False
    )
    op.create_index(
        op.f("ix_claims_is_deleted"), "claims", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_claims_patient_id"), "claims", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_claims_practitioner_id"), "claims", ["practitioner_id"], unique=False
    )
    op.create_index(
        op.f("ix_claims_provider_id"), "claims", ["provider_id"], unique=False
    )
    op.create_table(
        "diagnosis_service_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("diagnosis_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("insurer_id", sa.Integer(), nullable=True),
        sa.Column("is_covered", sa.Boolean(), nullable=False),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["diagnosis_id"],
            ["diagnosis_codes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["insurer_id"],
            ["insurance_companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["service_codes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_diagnosis_service_rules_is_deleted"),
        "diagnosis_service_rules",
        ["is_deleted"],
        unique=False,
    )
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("""CREATE FUNCTION nphies_audit_update() RETURNS trigger AS $$
        BEGIN
          NEW.created_at = OLD.created_at;
          NEW.updated_at = clock_timestamp();
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql""")
        op.execute(
            "CREATE TRIGGER audit_update BEFORE UPDATE ON diagnosis_codes FOR EACH ROW EXECUTE FUNCTION nphies_audit_update()"
        )
        op.execute(
            "CREATE TRIGGER audit_update BEFORE UPDATE ON organizations FOR EACH ROW EXECUTE FUNCTION nphies_audit_update()"
        )
        op.execute(
            "CREATE TRIGGER audit_update BEFORE UPDATE ON patients FOR EACH ROW EXECUTE FUNCTION nphies_audit_update()"
        )
        op.execute(
            "CREATE TRIGGER audit_update BEFORE UPDATE ON service_codes FOR EACH ROW EXECUTE FUNCTION nphies_audit_update()"
        )
        op.execute(
            "CREATE TRIGGER audit_update BEFORE UPDATE ON coverages FOR EACH ROW EXECUTE FUNCTION nphies_audit_update()"
        )
        op.execute(
            "CREATE TRIGGER audit_update BEFORE UPDATE ON encounters FOR EACH ROW EXECUTE FUNCTION nphies_audit_update()"
        )
        op.execute(
            "CREATE TRIGGER audit_update BEFORE UPDATE ON insurance_companies FOR EACH ROW EXECUTE FUNCTION nphies_audit_update()"
        )
        op.execute(
            "CREATE TRIGGER audit_update BEFORE UPDATE ON practitioners FOR EACH ROW EXECUTE FUNCTION nphies_audit_update()"
        )
        op.execute(
            "CREATE TRIGGER audit_update BEFORE UPDATE ON claims FOR EACH ROW EXECUTE FUNCTION nphies_audit_update()"
        )
        op.execute(
            "CREATE TRIGGER audit_update BEFORE UPDATE ON diagnosis_service_rules FOR EACH ROW EXECUTE FUNCTION nphies_audit_update()"
        )


def downgrade():
    raise RuntimeError(
        "Destructive downgrade disabled; restore a reviewed backup instead."
    )
