"""Add local JWT identities and persistent account lockouts."""

from alembic import op
import sqlalchemy as sa

revision = "0002_auth"
down_revision = "0001_warehouse"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("token_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "failed_login_attempts", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('admin', 'provider')", name="ck_user_role"),
        sa.CheckConstraint("failed_login_attempts >= 0", name="ck_user_login_attempts"),
        sa.CheckConstraint("token_version >= 0", name="ck_user_token_version"),
        sa.CheckConstraint(
            "username = lower(username)", name="ck_user_username_lowercase"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_users_is_deleted"), "users", ["is_deleted"], unique=False)
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "CREATE TRIGGER audit_update BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION nphies_audit_update()"
        )


def downgrade():
    raise RuntimeError(
        "Deleting authentication records requires a reviewed recovery plan."
    )
