"""Append-only authentication and claim audit events."""

from alembic import op
import sqlalchemy as sa

revision = "0003_audit_logs"
down_revision = "0002_auth"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("endpoint", sa.String(length=128), nullable=False),
        sa.Column("client_ip", sa.String(length=64), nullable=True),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('success', 'failure')", name="ck_audit_outcome"
        ),
        sa.CheckConstraint("http_status BETWEEN 100 AND 599", name="ck_audit_status"),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_created_at", "audit_logs", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_actor_user_id"),
        "audit_logs",
        ["actor_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_is_deleted"), "audit_logs", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_request_id"), "audit_logs", ["request_id"], unique=False
    )
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "CREATE TRIGGER audit_update BEFORE UPDATE ON audit_logs FOR EACH ROW EXECUTE FUNCTION nphies_audit_update()"
        )
        op.execute("""CREATE FUNCTION reject_audit_mutation() RETURNS trigger AS $$
        BEGIN RAISE EXCEPTION 'Audit records are append-only'; END;
        $$ LANGUAGE plpgsql""")
        op.execute(
            "CREATE TRIGGER prevent_audit_mutation BEFORE UPDATE OR DELETE ON audit_logs FOR EACH ROW EXECUTE FUNCTION reject_audit_mutation()"
        )
        op.execute(
            "CREATE TRIGGER prevent_audit_truncate BEFORE TRUNCATE ON audit_logs FOR EACH STATEMENT EXECUTE FUNCTION reject_audit_mutation()"
        )


def downgrade():
    raise RuntimeError("Audit history cannot be removed by automatic downgrade.")
